src/Darts/Controllers/DartsController.cs
using System;
using System.Collections.Generic;
using Darts.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Darts.Models.ViewModels.SpelerViewModels;

namespace Darts.Controllers
{
    [Authorize(Policy = "Speler")]
    public class DartsController : Controller
    {
        private readonly ISpelerRepository _spelerRepository;
        private readonly IWedstrijdRepository _wedstrijdRepository;
        private readonly ISpelerWedstrijdRepository _spelerWedstrijdRepository;

        public DartsController(ISpelerRepository spelerRepository,
            IWedstrijdRepository wedstrijdRepository,
            ISpelerWedstrijdRepository spelerWedstrijdRepository)
        {
            _spelerRepository = spelerRepository;
            _wedstrijdRepository = wedstrijdRepository;
            _spelerWedstrijdRepository = spelerWedstrijdRepository;
        }

        //volgende overschrijven auth van class level
        public IActionResult Index()
        {
            IEnumerable<Speler> spelers = _spelerRepository.GetAll();
            return View(spelers);
        }

        public IActionResult Detail(int id)
        {
            Speler s = _spelerRepository.GetById(id);
            ViewData["Speler"] = s.Voornaam + " " + s.Naam;
            IEnumerable<SpelerWedstrijd> wedstrijden = _spelerWedstrijdRepository.GetBySpelerId(id);
            return View(wedstrijden);
        }
        [HttpGet]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult Edit(int id)
        {
            Speler speler = _spelerRepository.GetById(id);
            if (speler == null)
                return NotFound();
            //ViewData["Locations"] = GetLocationsAsSelectList(brewer.Location?.PostalCode);
            return View(new EditViewModel(speler));
        }

        [HttpGet]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult NieuweWedstrijd()
        {
            ViewData["Spelers"] = GetSpelersAsSelectList();
            return View(new WedstrijdViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult NieuweWedstrijd(WedstrijdViewModel spelerwedstrijd)
        {
            if (ModelState.IsValid && (spelerwedstrijd.IdSpeler1 != spelerwedstrijd.IdSpeler2))
            {
                try
                {
                    Speler speler1 = _spelerRepository.GetById(spelerwedstrijd.IdSpeler1);
                    Speler speler2 = _spelerRepository.GetById(spelerwedstrijd.IdSpeler2);
                    Wedstrijd w = new Wedstrijd(spelerwedstrijd.DatumGespeeld);

                    SpelerWedstrijd sw1 = new SpelerWedstrijd(speler1, w, spelerwedstrijd.PuntenGewonnen, speler2.Voornaam + " " + speler2.Naam);
                    SpelerWedstrijd sw2 = new SpelerWedstrijd(speler2, w, spelerwedstrijd.PuntenVerloren, speler1.Voornaam + " " + speler1.Naam);

                    _spelerWedstrijdRepository.Add(sw1);
                    _spelerWedstrijdRepository.Add(sw2);
                    _spelerWedstrijdRepository.SaveChanges();

                    TempData["message"] = $"Nieuwe wedstrijd tussen {speler1.VolledigeNaam} en {speler2.VolledigeNaam} werd met succes toegevoegd!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            ViewData["Spelers"] = GetSpelersAsSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult Edit(EditViewModel spelerEditViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Speler speler = _spelerRepository.GetById(spelerEditViewModel.SpelerId);
                    MapSpelerEditViewModelToSpeler(spelerEditViewModel, speler);
                    _spelerRepository.SaveChanges();
                    TempData["message"] = $"{speler.Naam} {speler.Voornaam} werd succesvol gewijzigd!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            //ViewData["Locations"] = GetLocationsAsSelectList(brewerEditViewModel?.PostalCode);
            return View(spelerEditViewModel);
        }

        [HttpGet]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult Create()
        {
            //ViewData["Locations"] = GetLocationsAsSelectList(null);
            return View(nameof(Edit), new EditViewModel(new Speler()));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult Create(EditViewModel spelerEditViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Speler speler = new Speler();
                    MapSpelerEditViewModelToSpeler(spelerEditViewModel, speler);
                    _spelerRepository.Add(speler);
                    _spelerRepository.SaveChanges();
                    TempData["message"] = $"{speler.Naam} {speler.Voornaam} werd succesvol toegevoegd!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            //ViewData["Locations"] = GetLocationsAsSelectList(brewerEditViewModel?.PostalCode);
            return View(nameof(Edit), spelerEditViewModel);
        }

        [Authorize(Policy = "AdminOnly")]
        public IActionResult Delete(int id)
        {
            Speler speler = _spelerRepository.GetById(id);
            if (speler == null)
                return NotFound();
            ViewData["Name"] = speler.Naam;
            return View();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOnly")]
        public IActionResult DeleteConfirmed(int id)
        {
            Speler speler = null;
            try
            {
                speler = _spelerRepository.GetById(id);
                _spelerRepository.Remove(speler);
                _spelerRepository.SaveChanges();
                TempData["message"] = $"{speler.Naam} {speler.Voornaam} werd succesvol verwijderd!";
            }
            catch
            {
                TempData["error"] = $"Er ging iets verkeerd, speler {speler?.Naam} {speler?.Voornaam} werd niet verwijderd...";
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Policy ="AdminOnly")]
        public IActionResult DeleteWedstrijd(int id)
        {
            Wedstrijd w = _wedstrijdRepository.GetById(id);
            if (w == null)
                return NotFound();
            ViewData["Datum"] = w.DatumGespeeld;
            return View();
        }

        [HttpPost, ActionName("DeleteWedstrijd")]
        [ValidateAntiForgeryToken]
        [Authorize(Policy ="AdminOnly")]
        public IActionResult DeleteWedstrijdConfirmed(int id)
        {
            Wedstrijd wedstrijd = null;
            try
            {
                wedstrijd = _wedstrijdRepository.GetById(id);
                _wedstrijdRepository.Remove(wedstrijd);
                _spelerRepository.SaveChanges();
                TempData["message"] = $"De wedstrijd van {wedstrijd.DatumGespeeld} werd succesvol verwijderd!";
            }
            catch
            {
                TempData["error"] = $"Er ging iets verkeerd, de wedstrijd van {wedstrijd.DatumGespeeld} werd niet verwijderd";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Info()
        {
            return View();
        }
        public IActionResult Spelers()
        {
            return View(_spelerRepository.GetAll());
        }

        //private SelectList GetLocationsAsSelectList(string postalCode)
        //{
        //    return new SelectList(
        //        _locationRepository.GetAll().OrderBy(l => l.Name),
        //        nameof(Location.PostalCode),
        //        nameof(Location.Name),
        //        postalCode);
        //}
        private SelectList GetSpelersAsSelectList()
        {
            return new SelectList(_spelerRepository.GetAll().OrderBy(s => s.Naam).ThenBy(s => s.Voornaam),
                nameof(Speler.Id),
                nameof(Speler.VolledigeNaam));
        }

        private void MapSpelerEditViewModelToSpeler(EditViewModel spelerEditViewModel, Speler speler)
        {
            speler.Naam = spelerEditViewModel.Naam;
            //speler.Email = spelerEditViewModel.Email;
            speler.Voornaam = spelerEditViewModel.Voornaam;
        }
    }
}

src/Darts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top shadow ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Darts" asp-action="Index" class="navbar-brand">Startpagina</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Darts" asp-action="Index">Rangschikking</a></li>
                    <li><a asp-area="" asp-controller="Darts" asp-action="Spelers">Spelers</a></li>
                    <li><a asp-area="" asp-controller="Darts" asp-action="Info">Info</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content shadow">
        @if (TempData["message"] != null) {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @if (TempData["error"] != null) {
            <div class="alert alert-warning">@TempData["error"]</div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Yves Vanduynslager</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>